hydra:
  run:
    dir: outputs/${experiment.name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${experiment.name}/${model.arch}_width${model.width}_seed${experiment.seed}
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  mode: MULTIRUN
  searchpath: []
  callbacks: {}
  output_subdir: .hydra
  overrides:
    hydra:
    - hydra.mode=MULTIRUN
    task:
    - experiment=transformer
    - experiment.seed=0,1
    - model.width=80,200,400
  job:
    name: main
    chdir: true
    override_dirname: experiment.seed=0,1,experiment=transformer,model.width=80,200,400
    id: ???
    num: ???
    config_name: config
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.3.2
    version_base: '1.3'
    cwd: /vast.mnt/home/20233308/MSc_Thesis
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: /vast.mnt/home/20233308/MSc_Thesis/configs
      schema: file
      provider: main
    - path: ''
      schema: structured
      provider: schema
    output_dir: ???
    choices:
      experiment: transformer
      training: base
      dataset: iwslt
      model: transformer
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: default
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: basic
      hydra/output: default
  verbose: false
model:
  arch: transformer
  trainer: seq2seq
  width: 80
  nhead: 8
  num_layers: 6
  dropout: 0.0
  tie_decoder_embeddings: true
  max_len: 5000
dataset:
  name: iwslt14
  src_lang: de
  tgt_lang: en
  data_dir: data/iwslt14
  tokenizer_model: data/iwslt14/iwslt14_bpe.model
  src_vocab_size: 32000
  tgt_vocab_size: 32000
  pad_idx: 0
  bos_idx: 1
  eos_idx: 2
  batch_size: 64
  num_workers: 4
  max_len: 200
  subset_fraction: 1
training:
  epochs: 30
  batch_size: 128
  optimizer: adam
  lr: 0.0005
  momentum: 0
  weight_decay: 0.0005
  lr_schedule: inverse_sqrt
  warmup_steps: 4000
  label_smoothing: 1
name: transformer
seed: 0
experiment:
  name: default
  seed: 0
  output_dir: outputs/${experiment.name}
